model = dict(
    type='DenoisingUnet',
    image_size=64,
    in_channels=3,
    base_channels=192,
    resblocks_per_downsample=3,
    attention_res=(32, 16, 8),
    dropout=0.1,
    num_classes=1000,
    use_fp16=True,
    attention_cfg=dict(type='MultiHeadAttentionBlock', num_heads=4, num_head_channels=64, use_new_attention_order=True),
    use_scale_shift_norm=True)

# image_size,
# in_channels,
# model_channels,
# out_channels,
# num_res_blocks,
# attention_resolutions,
# dropout = 0,
# channel_mult = (1, 2, 4, 8),
# conv_resample = True,
# dims = 2,
# num_classes = None,
# use_checkpoint = False,
# use_fp16 = False,
# num_heads = 1,
# num_head_channels = -1,
# num_heads_upsample = -1,
# use_scale_shift_norm = False,
# resblock_updown = False,
# use_new_attention_order = False
